name: Sync to Gitee

on:
  push:
    branches: [main, master] # 在推送到这些分支时触发同步
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/Toolmanele # 源仓库
          dst: gitee/Toolmanele # 目标仓库
          dst_token: ${{ secrets.GITEE_PASSWORD }} # 确保这是 HTTPS 令牌
          clone_style: https # 强制使用 HTTPS 克隆
          ssh: false
          account_type: user # 如果是组织仓库使用 org，个人用 user
          force_update: true # 强制更新
          static_list: "" # 静态同步列表
          debug: true # 调试模式
